### ISSUE TITLE
V2 Preview-1 OSX Ability to paste into New Project fields AB#16922

### ISSUE THREAD

**Issue by alancast** [Microsoft/VoTT#562]
**Is your feature request related to a problem? Please describe.**
Small simple one 😄 but I cannot copy and paste into fields when creating a new project. I was creating a project that already had a fleshed out description from elsewhere so I wanted to just copy and paste it into the description field but I couldn't ☹️ .

**Describe the solution you'd like**
The ability to paste into fields in the create project screen (Name, Description, potentially others and potentially in other places in the app, haven't found any others yet though)

The page that I am talking about:
![image](https://user-images.githubusercontent.com/3934092/52600068-4d6eb980-2e0f-11e9-9a15-cf5a1f85a251.png)

**Comment by wbreza** [comment]
@alancast - Thanks for the feedback.  This is currently a limitation of electron - but there are workarounds.

Even though you don't get a context menu to copy/paste in the fields standard `Ctrl/Command+V` should still allow you to cut/copy/paste within the fields.  Let me know if you see otherwise.

**Comment by wbreza** [comment]
Resolved in #570. Released in Preview 2
