### ISSUE TITLE
Evaluation Support

### ISSUE THREAD

**Issue by ScoGroMSFT** [microsoft/VoTT#795]
**Is your feature request related to a problem? Please describe.**
We use VOTT for labeling data. However, it would be great if we could load the output of a model and compare that against the labeled truth set. It would make VOTT a one-stop shopping trip for dealing with labeled data.

**Describe the solution you'd like**
There are a standard set of metrics, such as precision / recall / F-1 / accuracy that it could support. Ideally, a pluggable model that supported alternative evaluations would allow for extending the tool beyond what the owners have bandwidth to implement

**Describe alternatives you've considered**
We have built our own evaluation tools to solve the problem but it feels like writing code to address a problem that was effectively solved long ago is the wrong thing to do.

**Additional context**
Given that the step immediately after seeing an evaluation result (e.g. precision: X, recall: Y) would be to understand why the aggregate came out that way, it is also necessary to see the comparison between each record in the inference output & the expected label.

**Comment by JacopoMangiavacchi** [comment]
Hi Scott, thank you for your feedback but I'm not sure I completely understood the request here. 

Usually test/evaluation metrics (whatever metrics you're using) as well as confusion matrix are not exported within a model (whatever model format you use).  For the default SSD MobileNet model (in TF.js format) we are importing from Google we don't have these metrics and in order to get these we should train the full Coco dataset and this is not something we can do at the moment.  In any case even with a custom model again I don't think there is a standard way to export metrics and import these in VoTT.

Finally another thing that is not completely clear is the definition of label here.  In the context of an object detection labels the model is of course a multi-label classifier but the label is basically the tuple region/tag.  What happen if the prediction has the right tags but the corresponding regions are slightly different for example just by few pixels ?

Please let me know if you want to talk offline about this request.

**Comment by ScoGroMSFT** [comment]
Circling back with the details of our discussion:
**Clarifying the Request**
The feature request is to add the capability to load two datasets and compare them, outputting metrics like precision/recall, etc... 
This could be used to compare the labeling of multiple users or compare the output of a model against truthsets that aren't part of the training process. 

**Outcome of the Discussion**
This feature deviates from the core purpose of VOTT, which is aimed at making it easy for users to produce labeled datasets via a visual interface, so it's not the right fit for this tool.
The recommendation is to write/use separate tools for the tasks of comparing two datasets.
